version: '3.3'
services:
  application:
    build: .
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/burger'
      SPRING_DATASOURCE_USERNAME: 'user'
      SPRING_DATASOURCE_PASSWORD: 'password'
    ports:
      - '8080:8080'
    expose:
      - '8080'
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'burger'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'