apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-app-burger
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-burger-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50