apiVersion: v1
kind: Pod
metadata:
  name: app-burger
  labels:
    app: app-burger
spec:
  containers:
    - name: app-burger
      image: souzamarcos/burger-application:latest
      ports: 
        - containerPort: 8080
      env: 
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://svc-db-burger:3306/burger"
        - name: SPRING_DATASOURCE_USERNAME
          value: "user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"